"""Bounded, nonbinding transfer checks after an iteration; never promotes models.

Randomized starts are generated by fixed reference models, never by the candidate,
and used identically for baseline/candidate comparisons. This is a transfer probe,
not a claim of perfect play or a replacement for the sampled binding gate.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from match_evidence import atomic_json, file_hash, model_identity, runtime_identity
from worker_lease import worker_lease


def parser():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--candidate', required=True)
    ap.add_argument('--baseline', required=True)
    ap.add_argument('--opponent', action='append', required=True)
    ap.add_argument('--book-teacher', action='append', required=True)
    ap.add_argument('--human-game', action='append', default=[])
    ap.add_argument('--iteration-state')
    ap.add_argument('--raw-generation-dir')
    ap.add_argument('--replay-data-dir')
    ap.add_argument('--run-dir', required=True)
    ap.add_argument('--seed', type=int, default=140000000)
    ap.add_argument('--book-entries', type=int, default=120)
    ap.add_argument('--book-sims', type=int, default=700)
    ap.add_argument('--sims', type=int, default=3200)
    ap.add_argument('--free-games', type=int, default=200)
    ap.add_argument('--workers', type=int, default=8)
    ap.add_argument('--dry-run', action='store_true')
    return ap


def plan(args):
    directory = Path(args.run_dir)
    book = str(directory / 'independent_starts.json')
    command = ['tools/make_book.py']
    for teacher in args.book_teacher:
        command += ['--model', teacher]
    command += ['--entries', str(args.book_entries), '--plies', '8', '--sims', str(args.book_sims),
                '--temperature', '1.0', '--seed', str(args.seed), '--workers', str(args.workers),
                '--engine', 'native', '--oversample', '12', '--out', book]
    stages = [('starts', command, book)]
    if args.raw_generation_dir:
        output = str(directory / 'half_data_manifest.json')
        stages.insert(0, ('half_data', ['tools/generation_data_snapshot.py', '--raw-dir', args.raw_generation_dir,
                                      '--seed', '3173', '--output', output], output))
    if args.replay_data_dir:
        output = str(directory / 'replay_census.json')
        stages.insert(0, ('census', ['tools/replay_census.py', '--data-dir', args.replay_data_dir,
                                   '--output', output], output))
    for index, opponent in enumerate(args.opponent):
        # Same paired starts AND RNG block for candidate and baseline, per opponent.
        for label, model in (('baseline', args.baseline), ('candidate', args.candidate)):
            name = f'matched_{label}_opponent_{index}'
            output = str(directory / f'{name}.json')
            cmd = ['tools/match.py', '--model-a', model, '--model-b', opponent,
                   '--games', str(2 * args.book_entries), '--sims', str(args.sims),
                   '--workers', str(args.workers), '--engine', 'native',
                   '--seed', str(args.seed + 4000000 + index * 1000000),
                   '--book', book, '--book-offset', '0', '--report-path', output,
                   '--game-log', str(directory / f'{name}.jsonl'), '--resume']
            stages.append((name, cmd, output))
        name = f'free_candidate_opponent_{index}'
        output = str(directory / f'{name}.json')
        stages.append((name, ['tools/match.py', '--model-a', args.candidate, '--model-b', opponent,
                             '--games', str(args.free_games), '--sims', str(args.sims),
                             '--workers', str(args.workers), '--engine', 'native',
                             '--seed', str(args.seed + 7000000 + index * 1000000),
                             '--report-path', output, '--game-log', str(directory / f'{name}.jsonl'),
                             '--resume'], output))
    for index, human in enumerate(args.human_game):
        # Generic snapshots of the first ten complete turns of each known human
        # game, not selected using the new model's results. Never training input.
        rows = [json.loads(line) for line in Path(human).read_text(encoding='utf-8').splitlines() if line.strip()]
        cases = [str(row) for row in range(0, min(20, len(rows)), 2)]
        output = str(directory / f'human_{index}.json')
        stages.append((f'human_{index}', ['tools/probe_human_line.py', '--human-game', human,
                                        '--models', args.baseline, args.candidate, '--cases', *cases,
                                        '--sims', str(args.sims), '--seeds', '101', '211', '307',
                                        '--continue-plies', '5', '--output', output, '--resume'], output))
    return stages


def run(args):
    if not 1 <= args.workers <= 8 or not 0 < args.book_entries <= 1000 or args.free_games <= 0 or args.free_games % 2:
        raise ValueError('workers 1..8, book entries 1..1000, positive even free-game count required')
    if len(args.book_teacher) > 3 or len(args.opponent) > 2:
        raise ValueError('declared seed layout supports at most three book teachers and two opponents')
    stages = plan(args)
    if args.dry_run:
        print(json.dumps(stages, indent=2))
        return
    if args.iteration_state:
        state = json.loads(Path(args.iteration_state).read_text(encoding='utf-8'))
        if state['status'] not in ('passed_not_promoted', 'rejected', 'inconclusive'):
            raise ValueError(f"iteration not safely completed: {state['status']}")
    manifest = {'config': {k: v for k, v in vars(args).items() if k != 'dry_run'},
                'models': [model_identity(p) for p in [args.candidate, args.baseline, *args.opponent, *args.book_teacher]],
                'humans': [model_identity(p) for p in args.human_game],
                'runtime': runtime_identity(), 'implementation': file_hash(__file__),
                'tools': {p: file_hash(ROOT / p) for p in ('tools/make_book.py', 'tools/probe_human_line.py',
                                                        'tools/generation_data_snapshot.py', 'tools/replay_census.py')},
                'plan': stages}
    directory = Path(args.run_dir)
    state_path = directory / 'state.json'
    if state_path.exists():
        status = json.loads(state_path.read_text(encoding='utf-8'))
        if status['manifest'] != json.loads(json.dumps(manifest)):
            raise ValueError('follow-up resume provenance changed')
    else:
        status = {'manifest': manifest, 'stages': {}, 'status': 'running', 'binding': False}
    atomic_json(state_path, status)
    for name, command, output in stages:
        previous = status['stages'].get(name, {})
        if previous.get('status') == 'complete':
            if not Path(output).is_file() or file_hash(output) != previous['sha256']:
                raise ValueError(f'completed follow-up output changed: {output}')
            continue
        status['stages'][name] = {'status': 'running', 'started': time.strftime('%Y-%m-%dT%H:%M:%S')}
        atomic_json(state_path, status)
        print(f'FOLLOW-UP {name}: {command}', flush=True)
        try:
            if name == 'starts':
                # The book builder predates worker leases; protect it here.
                if Path(output).exists():
                    raise ValueError('unrecorded start book exists; inspect before resuming')
                with worker_lease():
                    subprocess.run([sys.executable, '-u', *command], cwd=ROOT, check=True)
            else:
                subprocess.run([sys.executable, '-u', *command], cwd=ROOT, check=True)
            report = json.loads(Path(output).read_text(encoding='utf-8'))
            if name == 'starts' and len(report.get('entries', [])) != args.book_entries:
                raise ValueError('incomplete start set')
            if name.startswith(('matched_', 'free_')):
                expected = 2 * args.book_entries if name.startswith('matched_') else args.free_games
                if report.get('games') != expected:
                    raise ValueError('incomplete match')
            if name.startswith('human_') and not report.get('complete'):
                raise ValueError('incomplete human probe')
            status['stages'][name].update(status='complete', sha256=file_hash(output))
            atomic_json(state_path, status)
        except Exception as exc:
            status['status'] = 'failed'
            status['stages'][name].update(status='failed', error=str(exc))
            atomic_json(state_path, status)
            raise
    comparisons = []
    for index, opponent in enumerate(args.opponent):
        reports = {name: json.loads((directory / f'matched_{name}_opponent_{index}.json').read_text())
                   for name in ('baseline', 'candidate')}
        scores = {name: {'white': r['a_as_white']['score'], 'black': r['a_as_black']['score'],
                         'overall': r['a_score']} for name, r in reports.items()}
        comparisons.append({'opponent': opponent, 'scores': scores,
                            'candidate_minus_baseline': {color: scores['candidate'][color] - scores['baseline'][color]
                                                         for color in ('white', 'black', 'overall')}})
    atomic_json(directory / 'summary.json', {'binding': False, 'comparisons': comparisons,
                                            'interpretation': 'matched-start transfer check, not a perfect-play score or promotion verdict'})
    status['status'] = 'complete'
    atomic_json(state_path, status)
    print('Follow-up complete; no promotion or binding verdict changes.', flush=True)


if __name__ == '__main__':
    run(parser().parse_args())
